switch to gsl v1.0.1 (#36)
* switch to gsl v1.0.1

* inspired by @musicinmybrain PR: https://github.com/openbraininstitute/MorphIO/pull/4
* Getting this in CI:
    + delocate-wheel --require-archs x86_64 -w /private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/repaired_wheel -v /private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/built_wheel/morphio-0.1.dev1-cp39-cp39-macosx_10_9_x86_64.whl
    INFO:delocate.delocating:Copying library /usr/local/Cellar/llvm@18/18.1.8/lib/libunwind.1.0.dylib to morphio/.dylibs/libunwind.1.0.dylib
    INFO:delocate.delocating:Modifying install name in morphio/_morphio.cpython-39-darwin.so from /usr/local/opt/llvm@18/lib/libunwind.1.dylib to @loader_path/.dylibs/libunwind.1.0.dylib
    Traceback (most recent call last):
    Fixing: /private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/built_wheel/morphio-0.1.dev1-cp39-cp39-macosx_10_9_x86_64.whl
      File "/private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/build/venv/bin/delocate-wheel", line 6, in <module>
        sys.exit(main())
      File "/private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/cmd/delocate_wheel.py", line 115, in main
        copied = delocate_wheel(
      File "/private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 1106, in delocate_wheel
        out_wheel_fixed = _check_and_update_wheel_name(
      File "/private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/build/venv/lib/python3.9/site-packages/delocate/delocating.py", line 928, in _check_and_update_wheel_name
        raise DelocationError(
    delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.9:
    /private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/tmpbzlbaa5d/wheel/morphio/.dylibs/libunwind.1.0.dylib has a minimum target of 14.0
    Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=14.0' to update minimum supported macOS for this wheel.
    [error]cibuildwheel: Command delocate-wheel --require-archs x86_64 -w /private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/repaired_wheel -v /private/var/folders/9n/h1d0pgxn4f5bbpg9mrrft9140000gn/T/cibw-run-mm_sqjzq/cp39-macosx_x86_64/built_wheel/morphio-0.1.dev1-cp39-cp39-macosx_10_9_x86_64.whl failed with code 1.
    [endgroup]

Try to work around this without setting `MACOSX_DEPLOYMENT_TARGET=14.0`